version: '3'

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass jobs
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=jobs
    volumes:
    - ./redis/redis-data:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf